### ISSUE TITLE
App navigation not working on Android

### ISSUE THREAD

**Issue by cange017** [ShellHacksFIU/ShellHacks-Mobile#5]
I'm getting these errors whenever I try to run the AppNavigator or Landing page and I am not sure why:

![screenshot_2018-08-07_134421 1](https://user-images.githubusercontent.com/32406498/43793016-4f7caa58-9a48-11e8-910d-7191e054f883.jpg)

![capture](https://user-images.githubusercontent.com/32406498/43792663-5ea4e3e8-9a47-11e8-86c6-d16496b28420.PNG)

**Comment by Jehfkemsy** [comment]
oh, I see what it is, there is a comment inside of the welcome folder that says "//full size " remove it and it should work... P.S. try fetching and running it before editing cuz I just fixed some stuff
